### ISSUE TITLE
How do you implement SDPG?

### ISSUE THREAD

**Issue by chulhongsung** [zhougroup/IDAC#11]
Dear authors,

Thanks for your great work on RL. 
 
In your works, you compared your works IDAC with SDPG(based on stable baseline). 

In both your repo and stable baseline, I can't find SDPG code. 

How can I get the SDPG code? 

Thanks!

**Comment by Zhendong-Wang** [comment]
Hi there, 

Thanks for your interest in our work! You can find the official SDPG code from https://github.com/rahulsinghchandraul/SDPG. If you want to build the SDPG from our framework, one simple try is to replace the IDAC actor with the DDPG actor, which is the SDPG from our version. You could also chose whether to use the Double-G trick. 

![WechatIMG21529](https://user-images.githubusercontent.com/43709979/193954354-f62301f4-dc63-4288-896c-a9ec59444880.jpeg)


Thanks!

**Comment by chulhongsung** [comment]
Thank you for your kindness!
