### ISSUE TITLE
In which part the distributional critic is created?

### ISSUE THREAD

**Issue by GoingMyWay** [zhougroup/IDAC#2]
Dear authors,

Thanks for this repo. TF is not that easy to read and In which part the distributional critic is created? How many Dirac delta functions you use?

Thank you.

**Comment by yuguangyue** [comment]
Hi, 

Thank you for your interest! The distributional critic is created in the **make_critics** function in file **policy_idac.py** ; we didn't use Dirac delta functions here, the way to control how many quantiles are used is by controlling the number of noises injected to this function, where the default number is 51.

**Comment by GoingMyWay** [comment]
> Hi,
> 
> Thank you for your interest! The distributional critic is created in the **make_critics** function in file **policy_idac.py** ; we didn't use Dirac delta functions here, the way to control how many quantiles are used is by controlling the number of noises injected to this function, where the default number is 51.

thanks, that is an interesting idea. Thank you.

**Comment by GoingMyWay** [comment]
How did you come up with this novel distributional idea? This is not that straightforward to think about.
