### ISSUE TITLE
Is there any docker file available?

### ISSUE THREAD

**Issue by sunjing1102628** [zhougroup/IDAC#3]
Thanks for your great work for distributional RL.
I will be appreciated if you can address some questions I have met.
1. Is there any docker file available? 
2. Also, I noticed that IDAC supports Tensorflow versions 1.15. Do you have planed and tested in higher versions, such as TensorFlow 2.5?
3. Which python version do you test, python 3.6 or python 3.7? 
Thanks for your early reply.

**Comment by yuguangyue** [comment]
Hello, thanks for your interest!
We do not have a docker file yet, and the currently implementation uses TF1. However, the environment setup is exactly the same with the requirements from the [stable-baselines](https://github.com/hill-a/stable-baselines). 
The python version is 3.7.

**Comment by sunjing1102628** [comment]
Thanks for your reply. I am appreciated for your great help.
In addition, do you have planed PyTorch version of this code?  
By the way, it is a great and deeply inspirational paper. Thanks for your contributions to Distributional Reinforcement Learning.

**Comment by Zhendong-Wang** [comment]
The PyTorch version is provided.
